#!/usr/bin/env bash
# =============================================================================
# pin-litellm-digest.sh — resolve a floating LiteLLM tag to an immutable digest
# and pin it into the gateway compose file (supply-chain control).
# =============================================================================
# Why: `ghcr.io/berriai/litellm:main-stable` is a MOVING tag. In a CMMC L2
# boundary the running image must be immutable and reproducible — you attest to
# a specific artifact, not "whatever main-stable was that day". This script
# resolves the tag to its `@sha256:...` digest and rewrites the compose `image:`
# line in place, then records the pin for evidence.
#
# Pairs with scripts/generate-sbom.sh (run it after pinning) and is documented
# in docs/litellm-supply-chain.md. See also ADR-roadmap Phase 0 (own-gateway).
#
# Usage:
#   scripts/pin-litellm-digest.sh                 # re-pin main-stable
#   scripts/pin-litellm-digest.sh v1.55.8-stable  # pin a specific release tag
#
# Needs: curl, python3. Network egress to ghcr.io (in the lab, add ghcr.io +
# its token endpoint to the Squid allowlist, or run from an admin workstation).
# =============================================================================
set -euo pipefail

IMAGE_REPO="berriai/litellm"
REGISTRY="ghcr.io"
TAG="${1:-main-stable}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE="${REPO_ROOT}/docker/gateway-host/docker-compose.yml"
PIN_RECORD="${REPO_ROOT}/docker/gateway-host/litellm.pinned"

[ -f "$COMPOSE" ] || { echo "compose not found: $COMPOSE" >&2; exit 1; }

echo "Resolving ${REGISTRY}/${IMAGE_REPO}:${TAG} ..." >&2

TOKEN="$(curl -fsSL \
  "https://${REGISTRY}/token?scope=repository:${IMAGE_REPO}:pull&service=${REGISTRY}" \
  | python3 -c "import sys,json;print(json.load(sys.stdin)['token'])")"

# HEAD the manifest; the registry returns the canonical digest in a header.
DIGEST="$(curl -fsSL -I \
  -H "Authorization: Bearer ${TOKEN}" \
  -H "Accept: application/vnd.oci.image.index.v1+json" \
  -H "Accept: application/vnd.docker.distribution.manifest.list.v2+json" \
  -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
  "https://${REGISTRY}/v2/${IMAGE_REPO}/manifests/${TAG}" \
  | tr -d '\r' | awk -F': ' 'tolower($1)=="docker-content-digest"{print $2}')"

case "$DIGEST" in
  sha256:*) ;;
  *) echo "failed to resolve digest (got: '${DIGEST:-<empty>}')" >&2; exit 1 ;;
esac

PINNED_REF="${REGISTRY}/${IMAGE_REPO}@${DIGEST}"
echo "resolved: ${PINNED_REF}" >&2

# Rewrite the single `image:` line for the litellm service, preserving indent.
python3 - "$COMPOSE" "$PINNED_REF" <<'PY'
import re, sys
path, ref = sys.argv[1], sys.argv[2]
src = open(path).read()
# Match the litellm service's image line (digest- or tag-pinned).
pat = re.compile(r'(?m)^(\s*image:\s*)ghcr\.io/berriai/litellm(?:@sha256:[0-9a-f]+|:[\w.\-]+)\s*$')
new, n = pat.subn(lambda m: m.group(1) + ref, src)
if n != 1:
    sys.exit(f"expected exactly 1 litellm image line, matched {n}")
open(path, "w").write(new)
print(f"updated {path}")
PY

# Record the pin for evidence (immutability attestation input).
UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
cat > "$PIN_RECORD" <<EOF
# LiteLLM image pin record (supply-chain evidence — docs/litellm-supply-chain.md)
# Regenerated by scripts/pin-litellm-digest.sh. Commit this file.
source_tag:   ${REGISTRY}/${IMAGE_REPO}:${TAG}
pinned_image: ${PINNED_REF}
digest:       ${DIGEST}
resolved_utc: ${UTC}
EOF

echo "wrote ${PIN_RECORD}" >&2
echo >&2
echo "Next: regenerate the SBOM for the pinned image:" >&2
echo "  scripts/generate-sbom.sh" >&2
